//! Prepare the scenario bundle embedded in browser builds.
//!
//! Browsers cannot discover `data/scenarios` at runtime, so the wasm target
//! gets a generated Rust lookup table containing every scenario in the
//! registry. Large render terrains are reduced to at most 512 samples on an
//! edge; simulation rasters and authored scenario data remain unchanged.

use serde::Deserialize;
use std::{
    env, fs,
    path::{Path, PathBuf},
};

#[derive(Deserialize)]
struct RegistryFile {
    scenarios: Vec<RegistryEntry>,
}

#[derive(Deserialize)]
struct RegistryEntry {
    id: String,
}

#[derive(Deserialize)]
struct TerrainMeta {
    rows: usize,
    cols: usize,
    posting_m: f32,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_dir = manifest_dir.join("../../data");
    let registry_path = data_dir.join("scenarios.json");
    println!("cargo:rerun-if-changed={}", registry_path.display());

    // Native builds read scenarios from disk and need no generated bundle.
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() != Ok("wasm32") {
        return;
    }

    let registry_bytes = fs::read(&registry_path).expect("read data/scenarios.json");
    let registry: RegistryFile =
        serde_json::from_slice(&registry_bytes).expect("parse data/scenarios.json");
    assert!(!registry.scenarios.is_empty(), "scenario registry is empty");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let terrain_out_dir = out_dir.join("web_scenarios");
    fs::create_dir_all(&terrain_out_dir).expect("create generated scenario directory");

    let mut generated = String::from(
        "// @generated by crates/scenario/build.rs; do not edit.\n\
         pub(crate) struct WebScenarioAssets {\n\
         \x20   pub metadata: &'static [u8],\n\
         \x20   pub terrain_metadata: &'static [u8],\n\
         \x20   pub terrain: &'static [u8],\n\
         \x20   pub vectors: &'static [u8],\n\
         \x20   pub population: &'static [u8],\n\
         \x20   pub fuel: &'static [u8],\n\
         \x20   pub dem: &'static [u8],\n\
         }\n",
    );
    generated.push_str(&format!(
        "pub(crate) const REGISTRY: &[u8] = include_bytes!({:?});\n",
        registry_path.to_string_lossy()
    ));
    generated.push_str(
        "pub(crate) fn scenario(id: &str) -> Option<WebScenarioAssets> {\n    match id {\n",
    );

    for entry in registry.scenarios {
        validate_id(&entry.id);
        let scenario_dir = data_dir.join("scenarios").join(&entry.id);
        assert!(scenario_dir.is_dir(), "registered scenario directory is missing: {}", entry.id);

        let metadata = scenario_dir.join("scenario.json");
        let terrain_metadata = scenario_dir.join("render_terrain.json");
        let source_terrain = scenario_dir.join("render_terrain.f32");
        let vectors = scenario_dir.join("osm.json");
        let population = scenario_dir.join("population.json");
        let fuel = scenario_dir.join("fuel.i32");
        let dem = scenario_dir.join("dem.f64");
        for path in [
            &metadata,
            &terrain_metadata,
            &source_terrain,
            &vectors,
            &population,
            &fuel,
            &dem,
        ] {
            assert!(path.is_file(), "missing scenario asset: {}", path.display());
            println!("cargo:rerun-if-changed={}", path.display());
        }

        let web_terrain = terrain_out_dir.join(format!("{}.f32", entry.id));
        reduce_terrain(&terrain_metadata, &source_terrain, &web_terrain);

        generated.push_str(&format!(
            "        {:?} => Some(WebScenarioAssets {{\n\
             \x20           metadata: include_bytes!({:?}),\n\
             \x20           terrain_metadata: include_bytes!({:?}),\n\
             \x20           terrain: include_bytes!({:?}),\n\
             \x20           vectors: include_bytes!({:?}),\n\
             \x20           population: include_bytes!({:?}),\n\
             \x20           fuel: include_bytes!({:?}),\n\
             \x20           dem: include_bytes!({:?}),\n\
             \x20       }}),\n",
            entry.id,
            metadata.to_string_lossy(),
            terrain_metadata.to_string_lossy(),
            web_terrain.to_string_lossy(),
            vectors.to_string_lossy(),
            population.to_string_lossy(),
            fuel.to_string_lossy(),
            dem.to_string_lossy(),
        ));
    }

    generated.push_str("        _ => None,\n    }\n}\n");
    fs::write(out_dir.join("web_scenarios.rs"), generated)
        .expect("write generated web scenario lookup");
}

fn validate_id(id: &str) {
    assert!(
        !id.is_empty()
            && id
                .bytes()
                .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_' || b == b'-'),
        "scenario id contains unsupported characters: {id:?}"
    );
}

fn reduce_terrain(metadata_path: &Path, source_path: &Path, output_path: &Path) {
    let metadata_bytes = fs::read(metadata_path).expect("read render_terrain.json");
    let metadata: TerrainMeta =
        serde_json::from_slice(&metadata_bytes).expect("parse render_terrain.json");
    let bytes = fs::read(source_path).expect("read render_terrain.f32");
    assert_eq!(
        bytes.len(),
        metadata.rows * metadata.cols * size_of::<f32>(),
        "terrain dimensions do not match {}",
        source_path.display()
    );

    let row_step = metadata.rows.div_ceil(512);
    let col_step = metadata.cols.div_ceil(512);
    // Terrain is square today. Keeping a single step preserves equal posting
    // in X and Y if a larger rectangular scenario is added later.
    let step = row_step.max(col_step).max(1);
    let out_rows = metadata.rows.div_ceil(step);
    let out_cols = metadata.cols.div_ceil(step);
    let mut reduced = Vec::with_capacity(out_rows * out_cols * size_of::<f32>());
    for row in (0..metadata.rows).step_by(step) {
        for col in (0..metadata.cols).step_by(step) {
            let offset = (row * metadata.cols + col) * size_of::<f32>();
            reduced.extend_from_slice(&bytes[offset..offset + size_of::<f32>()]);
        }
    }
    fs::write(output_path, reduced).expect("write reduced web terrain");

    // The loader derives the reduced dimensions and posting from the same
    // maximum edge rule. Assert it here so build-time preprocessing cannot
    // silently drift from runtime decoding.
    assert_eq!(out_rows, metadata.rows.div_ceil(step));
    assert_eq!(out_cols, metadata.cols.div_ceil(step));
    assert!(metadata.posting_m > 0.0, "terrain posting must be positive");
}
